name: CI/CD Deploy Java App to Tomcat10 on EC2

# Trigger deployment on push to staging or main, and on PR to staging
on:
  push:
    branches:
      - staging
      - master
  pull_request:
    branches:
      - staging

jobs:
  build:
    name: Build WAR
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Setup Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3 Build WAR file
      - name: Build WAR file
        run: mvn clean package -DskipTests

      # 4 Verify WAR file exists
      - name: Verify WAR file
        run: |
          echo "=== Listing target directory ==="
          ls -la target/
          
          echo "=== Checking for WAR files ==="
          if ls target/*.war 1> /dev/null 2>&1; then
            echo "Found WAR files:"
            ls -la target/*.war
            WAR_FILE=$(ls target/*.war | head -1)
            echo "WAR file: $WAR_FILE"
            
            # Verify it's a file, not directory
            if [ -d "$WAR_FILE" ]; then
              echo "ERROR: $WAR_FILE is a directory, not a file!"
              exit 1
            fi
            
            # Copy to a known location with correct name
            cp "$WAR_FILE" ./app.war
            echo "WAR_FILE copied to ./app.war"
          else
            echo "ERROR: No WAR files found in target directory"
            exit 1
          fi

      # 5 Upload WAR artifact for deployment jobs
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: ./app.war

      # 6 List WAR contents for debugging
      - name: List WAR contents
        run: |
          echo "=== Listing WAR file contents ==="
          jar tf ./app.war

  deploy-staging:
    name: Deploy to Staging
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    
    steps:
      # 1 Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./
          
      # 2 Verify artifact was downloaded
      - name: Verify artifact
        run: |
          echo "=== Checking current directory ==="
          ls -la
          echo "=== Checking if app.war exists ==="
          if [ -f "./app.war" ]; then
            echo "✓ app.war found"
            ls -la ./app.war
          else
            echo "✗ app.war not found"
            exit 1
          fi

      # 3 Create SSH key file
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 4 Test SSH connection
      - name: Test SSH connection
        run: |
          echo "=== Testing SSH connection ==="
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      # 5 Upload WAR file to server
      - name: Upload WAR file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.war"
          target: "/var/lib/tomcat10/webapps/staging.war"

      # 6 Deploy to Staging
      - name: Deploy to Staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Staging Deployment ==="
            
            # Clean up any existing staging artifacts
            echo "1. Cleaning up staging artifacts..."
            sudo rm -rf /var/lib/tomcat10/webapps/staging*
            
            # Set permissions for webapps directory
            echo "2. Setting permissions..."
            sudo chmod 777 /var/lib/tomcat10/webapps
            
            # Verify WAR file exists
            echo "3. Verifying WAR file..."
            if [ -f "/var/lib/tomcat10/webapps/staging.war" ]; then
              echo "✓ staging.war found"
            else
              echo "✗ staging.war not found"
              exit 1
            fi
            
            # Extract WAR file
            echo "4. Extracting WAR file..."
            cd /var/lib/tomcat10/webapps
            sudo mkdir -p staging
            sudo chown tomcat:tomcat staging
            sudo chmod 755 staging
            cd staging
            sudo jar -xf ../staging.war
            sudo chown -R tomcat:tomcat .
            sudo chmod -R 755 .
            
            # Check for index.jsp
            echo "5. Checking for index.jsp..."
            if [ -f "index.jsp" ]; then
              echo "✓ index.jsp found"
            else
              echo "⚠ index.jsp not found in staging directory"
              echo "Available files in staging root:"
              ls -la
              echo "Checking for other common index files..."
              if [ -f "index.html" ]; then
                echo "✓ index.html found"
              else
                echo "⚠ No index file found in staging root"
              fi
            fi
            
            # Check for web.xml
            echo "6. Checking for web.xml..."
            if [ -f "WEB-INF/web.xml" ]; then
              echo "✓ web.xml found"
            else
              echo "⚠ web.xml not found in WEB-INF/"
              echo "Available files in WEB-INF:"
              ls -la WEB-INF/
            fi
            
            # Set permissions for all files
            echo "7. Setting permissions..."
            sudo chown -R tomcat:tomcat /var/lib/tomcat10/webapps/staging
            sudo chmod -R 755 /var/lib/tomcat10/webapps/staging
            
            # Restart Tomcat
            echo "8. Restarting Tomcat..."
            sudo systemctl restart tomcat10
            
            # Wait for Tomcat to start
            echo "9. Waiting for Tomcat to start..."
            sleep 30
            
            # Verify deployment
            echo "10. Verifying deployment..."
            ls -la /var/lib/tomcat10/webapps/
            ls -la /var/lib/tomcat10/webapps/staging/
            
            # Check Tomcat status
            echo "11. Checking Tomcat status..."
            sudo systemctl status tomcat10 --no-pager
            
            echo "=== Staging Deployment Completed ==="

  deploy-production:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      # 1 Download WAR artifact
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: ./
          
      # 2 Verify artifact was downloaded
      - name: Verify artifact
        run: |
          echo "=== Checking current directory ==="
          ls -la
          echo "=== Checking if app.war exists ==="
          if [ -f "./app.war" ]; then
            echo "✓ app.war found"
            ls -la ./app.war
          else
            echo "✗ app.war not found"
            exit 1
          fi

      # 3 Create SSH key file
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 4 Test SSH connection
      - name: Test SSH connection
        run: |
          echo "=== Testing SSH connection ==="
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      # 5 Upload WAR file to server
      - name: Upload WAR file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "app.war"
          target: "/var/lib/tomcat10/webapps/ROOT.war"

      # 6 Deploy to Production
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "=== Starting Production Deployment ==="
            
            # Clean up any existing production artifacts
            echo "1. Cleaning up production artifacts..."
            sudo rm -rf /var/lib/tomcat10/webapps/ROOT*
            
            # Set permissions for webapps directory
            echo "2. Setting permissions..."
            sudo chmod 777 /var/lib/tomcat10/webapps
            
            # Verify WAR file exists
            echo "3. Verifying WAR file..."
            if [ -f "/var/lib/tomcat10/webapps/ROOT.war" ]; then
              echo "✓ ROOT.war found"
            else
              echo "✗ ROOT.war not found"
              exit 1
            fi
            
            # Extract WAR file
            echo "4. Extracting WAR file..."
            cd /var/lib/tomcat10/webapps
            sudo mkdir -p ROOT
            sudo chown tomcat:tomcat ROOT
            sudo chmod 755 ROOT
            cd ROOT
            sudo jar -xf ../ROOT.war
            sudo chown -R tomcat:tomcat .
            sudo chmod -R 755 .
            
            # Check for index.jsp
            echo "5. Checking for index.jsp..."
            if [ -f "index.jsp" ]; then
              echo "✓ index.jsp found"
            else
              echo "⚠ index.jsp not found in ROOT directory"
              echo "Available files in ROOT root:"
              ls -la
              echo "Checking for other common index files..."
              if [ -f "index.html" ]; then
                echo "✓ index.html found"
              else
                echo "⚠ No index file found in ROOT root"
              fi
            fi
            
            # Check for web.xml
            echo "6. Checking for web.xml..."
            if [ -f "WEB-INF/web.xml" ]; then
              echo "✓ web.xml found"
            else
              echo "⚠ web.xml not found in WEB-INF/"
              echo "Available files in WEB-INF:"
              ls -la WEB-INF/
            fi
            
            # Set permissions for all files
            echo "7. Setting permissions..."
            sudo chown -R tomcat:tomcat /var/lib/tomcat10/webapps/ROOT
            sudo chmod -R 755 /var/lib/tomcat10/webapps/ROOT
            
            # Restart Tomcat
            echo "8. Restarting Tomcat..."
            sudo systemctl restart tomcat10
            
            # Wait for Tomcat to start
            echo "9. Waiting for Tomcat to start..."
            sleep 30
            
            # Verify deployment
            echo "10. Verifying deployment..."
            ls -la /var/lib/tomcat10/webapps/
            ls -la /var/lib/tomcat10/webapps/ROOT/
            
            # Check Tomcat status
            echo "11. Checking Tomcat status..."
            sudo systemctl status tomcat10 --no-pager
            
            echo "=== Production Deployment Completed ==="
